DirectoryPath: "."
EnforceHTTPS: false
IgnoreURLs:
  - "https://fonts.googleapis.com"
  - "https://fonts.gstatic.com"
IgnoreDirs: []
IgnoreAltMissing: true
CheckInternalHash: false
#CacheExpires: "6h"